deploy-test

diff --git a/.github/workflows/vps_deploy.yml b/.github/workflows/vps_deploy.yml
--- a/.github/workflows/vps_deploy.yml
+++ b/.github/workflows/vps_deploy.yml
@@ -13,14 +13,15 @@ jobs:
     steps:
     - name: 📥 Checkout Code
       uses: actions/checkout@v4
+
     - name: Debug info
       run: echo "Branch is ${{ github.ref }} / ${{ github.head_ref }}"
       
-    - name: 🛑 Stop Current Services
-      run: |
-        echo "Stopping project-specific services..."
-        docker stop local-mongo local-redis fastapi_server 2>/dev/null || echo "Some containers not running"
-        docker rm fastapi_server 2>/dev/null || echo "Some containers not found"
+    # - name: 🛑 Stop Current Services
+    #   run: |
+    #     echo "Stopping project-specific services..."
+    #     docker stop broker-rabbitmq fastapi_server 2>/dev/null || echo "Containers not running"
+    #     docker rm broker-rabbitmq fastapi_server 2>/dev/null || echo "Containers not found"
         
     - name: 🧹 Clean Up Old Images (Optional)
       run: |
